version: "3.4"
services:
  api:
    build: ../common/api/
    command:
    - --cors
    - --db-connection
    - fdbk_mongodb_plugin
    - mongodb://db
  ui:
    build: ../common/ui/
    ports:
    - 8080:80
    volumes:
    - ./config.js:/app/config.js
  reporter:
    build: .
    command:
    - -v
    - -i
    - "15"
    - -n
    - "3"
    - --db-connection
    - fdbk_mongodb_plugin
    - mongodb://db
  db:
    image: mongo:4-bionic
