language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script:
- pycodestyle fdbk
- pylint -E --enable=invalid-name,unused-import,useless-object-inheritance fdbk
- coverage run --branch --source fdbk/ -m unittest discover -s tst/
- coverage report -m
deploy:
  provider: pypi
  user: __token__
  password:
    secure: sesy9Vzuu/AIIyEKEtHOJ5LtxHW4fgOS1WhvUtB4hDiZjVhj58OH4e6wkEqiTKGQCSP9cG0ZoN4xRyjaONSCfd65KjFvesZaNK8U3mB/SYXRMX7cDXKKuGsSqQP1/tCF8Z3eGbT7FXFL7q4l9jaVnb4KF5c/RkN3urxwYuchQ0ZEV8br2W37tZl6wgAtj8jgKvjXk3HIMezXg2w/EJ0xbUsaEEe1MoMOyT0FgkKlPErBKLFF0m6Jkdw6AoGV7oJGM+dgW7DCpm50XsbPZksT07ps5k4ekIlA8MXlscuEVFWx+X1azaVBn7TVzLZOOwFI7vF6HybnSPPa+FQ23abm4OuujBXWTTDEsmgWSCG2jNs7iJtKxjqYEKQKfTDls32Yrg5fGNMqV1SDzdb85TXnnwsANfNtB+dUPEJN74askfnmN9FRuh9pjB75IsN08pfrTj42r9IdqOSb91rEjOuADsprsCH4xBMd/fxwdC+Jo/uc+cAdoI2AGeuobQ7LNtJsvwXeqk+E7ITwn3H+YmtFx2Pl/du64oHt+C1Ywg6XP1agZu6E4NzwTYL9YtZOEbP3Fm96y/rrau+HZQdOuGQyZEHk5G3dP5ZB8Q/ESM1iKgX1zhNF1AN6B6ZXWNq95oUxg+ldgIs18pjBmE94UwOrrFUzji4AJuazNl2bkalT+1I=
  on:
    tags: true
    python: 3.6
