version: "3.4"
services:
  api:
    build: ../common/api/
    command:
    - --cors
    - --db-connection
    - fdbk_mongodb_plugin
    - mongodb://db
  ui:
    build: ../common/ui/
    ports:
    - 8080:80
    volumes:
    - ./config.js:/app/config.js
  init:
    build: .
    command:
    - -v
    - --db-connection
    - fdbk_mongodb_plugin
    - mongodb://db
    - create
    - --name
    - Test
    - -c
    - python
    - -u
    - process_simulator.py
  exec:
    build: .
    command:
    - -v
    - --db-connection
    - fdbk_mongodb_plugin
    - mongodb://db
    - exec
    - --console-as-json
    - --name
    - Test
  db:
    image: mongo:4-bionic
